### ISSUE TITLE
Missing support for ES2015 backtick interpolations involving "//"

### ISSUE THREAD

**Issue by jceipek** [davidrios/pug-tmbundle#1]
Pug no longer supports interpolation inside attributes using the hash brace syntax `"#{ }"`. It does support ES2015 template literals ``${ }`` (see https://github.com/pugjs/pug/issues/2346).

However, the syntax definition in `pug-tmbundle` breaks when these literals include `//`, which shows up near the start of URI schemes like `http`, `file`, etc...

Here's an example usecase:

```
a(href=`http://twitter.com/${twitter_handle}`) @#{twitter_handle}
```

Everything from the `//` onwards on the same line gets treated as a comment and the remainder of the file stops syntax highlighting properly.

<img width="896" alt="screen shot 2016-05-06 at 6 33 14 pm" src="https://cloud.githubusercontent.com/assets/438112/15089497/0b9a29b8-13b9-11e6-8cc9-ca05ff97740e.png">

**Comment by davidrios** [comment]
I could fix this on my end, but I'm wondering if I should. If you're writing ES6 code you probably should have an ES6 plugin, like Babel, in which case you won't have that problem. On the other hand, if I fix it on my end you'll loose ES6 highlighting if you do use a plugin, like this:

If you use Babel:
![screenshot - 05072016 - 02 32 50 pm](https://cloud.githubusercontent.com/assets/1418372/15093508/ad76c5f0-1460-11e6-958f-459750d87289.png)

and if I fix it on my end:
![screenshot - 05072016 - 02 33 08 pm](https://cloud.githubusercontent.com/assets/1418372/15093509/b0a33902-1460-11e6-9919-d0c33a59baac.png)

**Comment by jceipek** [comment]
As far as I can tell, pug uses the node.js javascript engine, which has supported template literals for a long time (see http://node.green/#template-literals).

I would be fine using an ES2015 (ES6) plugin; in fact I have https://github.com/babel/babel-sublime installed right now. I could be missing something obvious, but I'm not sure how to "stack" the syntax highlighting for Pug and ES2015 in Sublime Text without manually editing `tmbundle`s. Is that possible?

**Comment by davidrios** [comment]
I was indeed talking about the editor, not the interpreter. tmbundle highlighters can reference one another, I reference the javascript highlighter when I detect a javascript code block. I also have babel-sublime installed and for some reason in my editor it automatically replace the default javascript bundle when another bundle includes javascript. I'll have to investigate why that happens here.

**Comment by jceipek** [comment]
That's interesting. There's two immediate things I can think of that might be the culprit:
- I'm using Sublime Text 3 (the `README` mentions that you use v 2, right?)
- There's a way to set up babel-sublime to be the default javascript definition and I haven't set it to do that -- much of the code I write is still vanilla JS with no translation step. Did you override the default javascript package?
