### ISSUE TITLE
"style." breaks the syntax highlighter

### ISSUE THREAD

**Issue by Dan503** [davidrios/pug-tmbundle#12]
Every time without fail the pug syntax highlighting will completely break after a style element followed by a "." is used.

`````pug
p this paragraph #[strong will] have the correct highlighting

//-this will break the pug highlighter and throw an error even though it is valid pug syntax
style.
    .element { background: red; }

p this paragraph will #[strong not] have any highlighting
`````

It displays this error message when the pug template contains a dotted style block:

`````
empty range in char class in regex (?=[\w.:#\[*-&]|@nest)
``````

**Comment by alexkuz** [comment]
Also, this template would crash Sublime completely:
```pug
style(type='text/css').
      body {
        margin: 1rem;
      }
```

**Comment by luxlogica** [comment]
@Dan503 , @alexkuz can you confirm whether this bug has been fixed? I've just tried both your examples with the current stable build of Sublime - build 3126 - and the Pug package, and they both seem to work fine...

**Comment by abrenneke** [comment]
This is still happening for me. Pug package 1.0.1, Sublime 3 build 3175

**Comment by brwnrclse** [comment]
Hello, this issue is still happening for me 3190.

I found a similar bug and fix in different language tmbundle repository but maybe the solution here is similar?

https://github.com/alexlouden/Terraform.tmLanguage/commit/cc9fb7e02874929c73542db47283f7583bbbd6fd

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.
