### ISSUE TITLE
Highlight in context

### ISSUE THREAD

**Issue by undercloud** [davidrios/pug-tmbundle#14]
Please add feature use syntax highlight outside of *.pug files?

I wish:
```PHP
<?php

class Page
{
	public function render()
	{
		return (
			// @pug-annotation
			'!!!
				html
					div.class Hello
					span#id(attr="value") Pug'
		);
	}
}

```

**Comment by luxlogica** [comment]
@undercloud the problem in your example may be with the PHP syntax highlighter, not Pug's - that is, the highlighter that is 'in charge' of the file overall is the PHP highlighter, as this is a `.php` file, not a `.pug`. If you want the PHP highlighter to "see" embedded snippets of other languages, then it needs to know to "look for" them. This may be a feature that needs to be asked of the guys developing the PHP syntax highlighter.

Also, I believe that `!!!` is probably HAML syntax, not Pug. To add a doctype declaration in Pug you'd use `doctype html`, like this:

``` pug
doctype html
html
    head
        title Hello Pug
    body
        div.my-class
            span#my-id(data-attr="somevalue") Hello Pug
```

**Comment by undercloud** [comment]
ok) thx!
