### ISSUE TITLE
Embedded PHP Causes Highlighting Error

### ISSUE THREAD

**Issue by luxlogica** [davidrios/pug-tmbundle#15]
It seems that the current Pug syntax highlighter has trouble with PHP tags. It is probably not setup to identify PHP's opening - `<?php` - and closing - `?>` tags, so it it seems to think that the closing `>` is mismatched. This is what we see in Sublime Text 3 (Build 3126):

<img width="297" alt="screen shot 2017-09-08 at 8 02 22 pm" src="https://user-images.githubusercontent.com/2994472/30206837-b69dca2e-94d0-11e7-8759-acd2b5d452e9.png">

The issue also happens if we use PHP short tags syntax - i.e., `<?` and `<?=` opening tags.

This does not seem to happen inside interpolated tags - i.e., in the example below, the highlighter just parses everything as plain text:

<img width="728" alt="screen shot 2017-09-08 at 8 11 06 pm" src="https://user-images.githubusercontent.com/2994472/30207248-3659c5aa-94d2-11e7-8950-92413ca7724d.png">

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.
