### ISSUE TITLE
Syntax highlighting breaks when a string+variable are not inside (brackets)

### ISSUE THREAD

**Issue by campbellgoe** [davidrios/pug-tmbundle#16]
When setting an id for an element with a variable concatenated to a string, the syntax highlighting breaks the rest of the file. 
For example:
`elementName(id="string"+variableName)`
In my case:
`div(id="btn-"+id)`
Compiles correct html, but the syntax does not get highlighted correctly, and so a workaround is to use:
`div(id=("btn-"+id))`

**Comment by msftrncs** [comment]
@GCDeveloper, what editor are you using?  Is this still an issue?

**Comment by campbellgoe** [comment]
It was in Sublime Text 3, I no longer use that editor so I do not know.

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.
