### ISSUE TITLE
Syntax highlighting breaks at :class

### ISSUE THREAD

**Issue by smalllong** [davidrios/pug-tmbundle#17]
`span(class='iconfont' :class='["icon-electricity"+batteryIcons[deviceInfo.battery]]' v-if='!charging')`
:class after class attribute when using Vue is valid, but the syntax highlighting breaks after :class.

**Comment by tijn** [comment]
I think I have the same issue; I found out that the syntax highlighting works fine but only if I use (at least) two spaces between the attributes. This should be easy to solve in the highlighter code, right?

**Comment by msftrncs** [comment]
@smalllong, @tijn what editor is the highlighting broken?

**Comment by tijn** [comment]
@msftrncs in Sublime Text. I'm using `Dev Channel, Build 3208` but the issue was already present in earlier versions.

**Comment by davidrios** [comment]
fixed in #32
