### ISSUE TITLE
Broken on stable Sublime Text 3

### ISSUE THREAD

**Issue by enzy** [davidrios/pug-tmbundle#18]
test.pug:

![image](https://user-images.githubusercontent.com/809888/33026367-8e6e12e2-ce10-11e7-84aa-a16fd3ad0d5e.png)
![image](https://user-images.githubusercontent.com/809888/33026415-a8d7bd68-ce10-11e7-952c-5415cafde35b.png)
![image](https://user-images.githubusercontent.com/809888/33026437-b604e07e-ce10-11e7-8d0b-25ba1251642f.png)
![image](https://user-images.githubusercontent.com/809888/33026501-dcd6d6bc-ce10-11e7-88e5-1a3a97fba95c.png)
![image](https://user-images.githubusercontent.com/809888/33026539-efa5a2be-ce10-11e7-89b6-82104496e286.png)
![image](https://user-images.githubusercontent.com/809888/33026553-fc78893e-ce10-11e7-9fde-daed67287719.png)

**Comment by Baegus** [comment]
Related to #22

**Comment by shakeelmohamed** [comment]
Is `+mix3().mix2class` (line 69 in your screenshot) valid syntax? I've never seen a class applied to the result of a mixin call

**Comment by enzy** [comment]
You can pass more classes or attributes into a mixin with `&attributes` syntax. (line 53)

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.
