### ISSUE TITLE
Why does Sublime Text snippet work only at the last row?

### ISSUE THREAD

**Issue by serjyamp** [davidrios/pug-tmbundle#19]
I'm trying to create my own snippet for Sublime Text 3. Here it is:
```xml
<snippet>
    <content><![CDATA[
// begin $1
.$1$2
// end $1
]]></content>
    <!-- Optional: Set a tabTrigger to define how to trigger the snippet -->
    <tabTrigger>di</tabTrigger>
    <!-- Optional: Set a scope to limit where the snippet will trigger -->
    <scope>source.pug, text.pug</scope>
</snippet>
```
but it works only at the last row of document. what's wrong?

![image](https://user-images.githubusercontent.com/8271649/35209465-28d3291a-ff5f-11e7-912e-25a253acb214.png)

**Comment by CydGoblin** [comment]
+1

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.
