### ISSUE TITLE
Pug grammar doesn't recognize span as anything more than text.pug

### ISSUE THREAD

**Issue by alexr00** [davidrios/pug-tmbundle#26]
_From @emersonp on November 8, 2018 23:1_

Steps to Reproduce:

1. Use a pug inline block

``` p: span```

2. span is recognized as text.pug instead of something more specific

_Copied from original issue: Microsoft/vscode#62817_

**Comment by alexr00** [comment]
@emersonp, can you give me an example of an editor or IDE that does this correctly please? I want to make sure I'm reproducing this the right way.

**Comment by alexr00** [comment]
_From @vscodebot[bot] on November 20, 2018 11:13_

This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by alexr00** [comment]
_From @lxmfly123 on December 2, 2018 6:33_

@alexr00 WebStorm does this correctly.

**Comment by alexr00** [comment]
_From @joexmdq on December 13, 2018 22:57_

@alexr00  Here is an example of VSCode (1.30.0) vs Sublime Text (3.1.1) and Atom (1.33.0):
![example1](https://user-images.githubusercontent.com/45812155/49972379-37787180-ff10-11e8-8fc6-330d51ddd5f7.png)

**Comment by alexr00** [comment]
@joexmdq, thanks for the example! Looks like this is a problem with the grammar we're using for pug.

**Comment by msftrncs** [comment]
I believe this issue was an issue of VSCode-TextMate and will be resolved with the release of VS Code 1.35 (May 2019).

**Comment by davidrios** [comment]
Closing as it was an issue with VS Code itself.
