### ISSUE TITLE
Block Expansion (nested tags) grammar recognition broken

### ISSUE THREAD

**Issue by alexr00** [davidrios/pug-tmbundle#28]
_From @Tenrys on January 3, 2019 16:58_

- VSCode Version: 1.30.1
- OS Version: Windows_NT x64 10.0.17763 (1809)

![](https://tenrys.pw/ShareX/2019/Jan/eGGv.gif)

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#65983_

**Comment by alexr00** [comment]
_From @Tenrys on January 3, 2019 20:23_

This also seems to be happening... 

![](https://tenrys.pw/ShareX/2019/Jan/zFyi.gif)

**Comment by neilsoult** [comment]
Is there any way I can help? I've had this issue for a long time now, I'd love to see it fixed

**Comment by alexr00** [comment]
After some good investigation by @neilsoult this appears to be an issue with VS Code TextMate.
