### ISSUE TITLE
Colon-prefixed attribute that is not the first attribute does not get correct scope

### ISSUE THREAD

**Issue by alexr00** [davidrios/pug-tmbundle#32]
From @pqvst in https://github.com/microsoft/vscode/issues/76373

A colon-prefixed attribute that is not the first attribute does not get the correct scope (whereas @-prefixed does). Colon-prefixed attributes are shorthand notation for Vue.js property binding.

Expected scope, from `:foo` on line 6:
```
entity.other.attribute-name.tag.pug
meta.tag.other
text.pug
```
Unexpected scope, from `:bar` on line 5:
```
variable.other.readwrite.js
attribute_value
meta.tag.other
text.pug
```

![image](https://user-images.githubusercontent.com/4990657/60397866-935abe80-9b1f-11e9-9a73-0596f70b884b.png)

```pug
body
  .foo(foo="foo" bar="bar")

  .foo(foo="foo" v-bind:bar="bar")
  .foo(foo="foo" :bar="bar")
  .foo(:foo="foo" bar="bar")
  
  .foo(foo="foo" :[bar]="bar")
  .foo(:[foo]="foo" bar="bar")

  .foo(foo="foo" v-on:bar="bar")
  .foo(foo="foo" @bar="bar")
  .foo(@foo="foo" bar="bar")

  .foo(foo="foo" @[bar]="bar")
  .foo(@[foo]="foo" bar="bar")
```

(It seems github syntax highlighting has the same issue)

**Comment by lopugit** [comment]
still :/

**Comment by lopugit** [comment]
I'm gonna have to start contributing to pug stuff
