### ISSUE TITLE
Regex: unmatched parenthesis

### ISSUE THREAD

**Issue by kjvdven** [davidrios/pug-tmbundle#33]
I was looking at the Pug.JSON-tmLanguage file, trying to figure out if I could add to the NOVA plugin. 
And checking the regex for name, class and id and I got an unmatched parenthesis. Is that correct?

https://regex101.com/r/RgVEOU/1

**Comment by davidrios** [comment]
That's because the regex backslashes have to be escaped in the JSON file. Just replace all ```\\``` by ```\``` and you are good. Don't forget to escape them again (replace all ```\``` by ```\\```) if you copy it from that site.
