### ISSUE TITLE
Inline HTML

### ISSUE THREAD

**Issue by Ocautator** [davidrios/pug-tmbundle#35]
The end tag should be </ instead of <\\
![](https://user-images.githubusercontent.com/60533323/127140613-6945ce94-8718-448c-9246-7d8c2eeaf3ca.png)

**Comment by davidrios** [comment]
Seems to work fine here:

![image](https://user-images.githubusercontent.com/1418372/205149193-34863ef7-ced1-4a4f-b87e-7a93286e51e6.png)

Which editor / config are you using?

**Comment by Ocautator** [comment]
sublime

**Comment by davidrios** [comment]
Latest version should fix this.
