### ISSUE TITLE
Opening .pug file freezes sublime text 3

### ISSUE THREAD

**Issue by krodriguez** [davidrios/pug-tmbundle#4]
Using Sublime Text 3, Dev Channel, Build 3122 and everytime I open a pug file it freezes sublime text fully to the point of having to force quit.

**Comment by davidrios** [comment]
Does the problem occurs only with that dev build? I got no problems with the latest stable build.

**Comment by molefrog** [comment]
@krodriguez Did you manage to solve the issue? I have the similar problem with stable 3124 build.

**Comment by davidrios** [comment]
Since build 3114 sublime is shipping with a new JavaScript highlighter that is not playing well with this bundle, could be that. Try installing Babel, which is an alternate JavaScript bundle, restart sublime and test if the problem persists.

**Comment by dereli** [comment]
Installing Babel and disabling internal JavaScript package resolves it.

`Preferences > ignored_packages > ["Vintage", "JavaScript"]

**Comment by davidrios** [comment]
Have you guys tried the latest stable build 3126? I tested here and it seems to have resolved the issue.

**Comment by dereli** [comment]
Build 3126 fixed for me too.

**Comment by davidrios** [comment]
I'm closing this as it seems to be resolved with newer builds of Sublime Text.

**Comment by Nexuist** [comment]
Hi,

I'm also using 3126 and encountering this force quit issue. I tried disabling the default javascript syntax and installing Babel but the same issue persists.
