### ISSUE TITLE
Angular 2 syntax breaks highlighting

### ISSUE THREAD

**Issue by SomeKittens** [davidrios/pug-tmbundle#5]
Happy user of your syntax bundle since we called this "Jade".  However, Angular 2 has to muck up the works:

![screen shot 2016-10-11 at 10 23 09 am](https://cloud.githubusercontent.com/assets/1616464/19280962/bbb6d7d8-8f9c-11e6-84c1-3ee8b3cdf204.png)

Note specifically the breakage after `[(ngModel)]`.  I assume it's detecting the close paren and thinks that's the end of the input properties.

I'd be happy to dig through and open a PR if you can point me in the right direction.

**Comment by neilfarted** [comment]
syntax is still broken in 2018.
My issue is block expansion + angular attributes. 
<img width="789" alt="screen shot 2018-11-06 at 11 20 04 am" src="https://user-images.githubusercontent.com/682460/48088103-f0cb8500-e1b5-11e8-85e0-f3d52e2b0f6b.png">
not all block expansion and angular attributes breaks:
<img width="764" alt="screen shot 2018-11-06 at 11 20 29 am" src="https://user-images.githubusercontent.com/682460/48088126-ff19a100-e1b5-11e8-8ebb-1c06cf2d849c.png">

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.
