### ISSUE TITLE
Does not support filters whatsoever?

### ISSUE THREAD

**Issue by avdaredevil** [davidrios/pug-tmbundle#7]
Hey, so when I have filters like `clean-css` on my CSS, or `:babel` on my _`script`_ blocks it simply does not work.. I presume because it's looking for the `.` (dot) token.

Example:

```pug
script: :uglify-js:babel
    console.log({
        a: 1,
        v: 2,
        z: 3,
    })
```

**Comment by akifo** [comment]
+1 👍 #9

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.
