### ISSUE TITLE
Attributes: Missing Color Coding

### ISSUE THREAD

**Issue by ar-rm** [davidrios/pug-tmbundle#8]
Hi,

Thanks for the bundle!

I just updated a project from `.jade` to `.pug` and starting using [Pug-tmbundle](https://github.com/davidrios/pug-tmbundle).

I noticed immediately that the color coding within attributes is missing. They look like comments. Also loud comments are brighter than before.

If I set the document syntax to `Jade` (your original bundle) the color coding is as expected.

![screen shot 2017-01-16 at 1-16 2 55 37pm](https://cloud.githubusercontent.com/assets/199155/21997292/816626b8-dbfc-11e6-8307-bd990f6df426.png)

![screen shot 2017-01-16 at 1-16 2 55 19pm](https://cloud.githubusercontent.com/assets/199155/21997295/8353e69a-dbfc-11e6-93b1-9bf28a78655e.png)

- I'm on Sublime Text 2 (2.0.2, Build 2221)
- I've tried uninstalling `Jade-tmbundle` and restarting ST2.

Is this as you intended or a bug?

Thanks!

**Comment by davidrios** [comment]
Hi,

I tested here and couldn't find any difference. Is it possible that you are using an old version of the Jade bundle?

**Comment by ar-rm** [comment]
I think I have the latest versions. Package Manager doesn't find anything that needs to be updated.

- Jade: 1.0.1 (2016.09.11.21.36.23)
- Pug: 1.0.1

I upgraded to ST 3 (Build 3126) and tried disabling the Jade plugin. Neither make a difference.

Could it be a conflict with another plugin? If yes, do you have ideas of good places (ex: plugin type) to start looking?

Thanks for the reply.

**Comment by davidrios** [comment]
Please comment if you think this is still relevant.

**Comment by ar-rm** [comment]
Agreed. It's no longer relevant.

Thanks for the followup :-)
